### ISSUE TITLE
Non-matching drugs collapse to one entry

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#115]
When doing a query on drugs, all drugs without matches in the database are returned together as a single, non-matched item (comma separated). This is also the case in the returned .tsv file.

@gspies, see if you can find out what's going on here.

**Comment by gspies** [comment]
@ahwagner, I have pushed my fix for this bug.

**Comment by ahwagner** [comment]
Great! Go ahead and submit a pull request into master, and I'll give it a review.

**Comment by susannasiebert** [comment]
This still appears to be a problem only in that when searching with multiple unmatched terms, only the first one appears in the list of unmatched terms. This isn't a problem in the interaction search by gene names.
